// Generated by Wrangler by running `wrangler types`

interface Env {
	DATABASE_URL: string;
	GOOGLE_PROJECT_ID: string;
	GOOGLE_PRIVATE_KEY: string;
	GOOGLE_CLIENT_EMAIL: string;
	NEXT_PUBLIC_projectId: string;
	NEXT_PUBLIC_apiKey: string;
	NEXT_PUBLIC_measurementId: string;
	NEXT_PUBLIC_OGP_URL: string;
	NEXT_PUBLIC_IMAGE_URL: string;
	SECRET_KEY: string;
	ENV: string;
	prisma: Fetcher;
	ASSETS: Fetcher;
}
