#:schema node_modules/wrangler/config-schema.json
name = "cloud-blog2"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
main = "server.ts"
assets = { directory = "./build/client" ,binding = "ASSETS"}

[observability]
enabled = true
