#:schema node_modules/wrangler/config-schema.json
name = "cloud-blog"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client" ,binding = "ASSETS"}

services = [
  { binding = "prisma", service = "prisma-accelerate-workers" }
]

[observability]
enabled = true

[limits]
cpu_ms = 10000

[placement]
mode = "smart"
